
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package AnalizadoresFCA;

import java_cup.runtime.Symbol;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintacticoFCA extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SimbolosFCA.class;
}

  /** Default constructor. */
  @Deprecated
  public SintacticoFCA() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintacticoFCA(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintacticoFCA(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\026\000\002\002\004\000\002\002\003\000\002\004" +
    "\004\000\002\004\003\000\002\004\004\000\002\004\003" +
    "\000\002\004\004\000\002\004\003\000\002\004\004\000" +
    "\002\004\003\000\002\005\004\000\002\005\003\000\002" +
    "\003\011\000\002\003\007\000\002\003\006\000\002\003" +
    "\010\000\002\003\010\000\002\003\010\000\002\006\006" +
    "\000\002\007\006\000\002\010\006\000\002\011\015" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\107\000\012\030\006\031\010\032\013\033\015\001" +
    "\002\000\016\002\ufffa\010\ufffa\030\ufffa\031\ufffa\032\ufffa" +
    "\033\ufffa\001\002\000\016\002\ufffe\010\ufffe\030\ufffe\031" +
    "\ufffe\032\ufffe\033\ufffe\001\002\000\004\012\100\001\002" +
    "\000\016\002\ufffc\010\ufffc\030\ufffc\031\ufffc\032\ufffc\033" +
    "\ufffc\001\002\000\004\007\075\001\002\000\004\002\074" +
    "\001\002\000\016\002\ufff8\010\ufff8\030\ufff8\031\ufff8\032" +
    "\ufff8\033\ufff8\001\002\000\004\007\071\001\002\000\014" +
    "\002\000\030\006\031\010\032\013\033\015\001\002\000" +
    "\004\007\016\001\002\000\016\022\021\023\020\025\026" +
    "\026\025\027\024\034\023\001\002\000\020\010\063\022" +
    "\021\023\020\025\026\026\025\027\024\034\023\001\002" +
    "\000\004\006\060\001\002\000\004\037\052\001\002\000" +
    "\020\010\ufff6\022\ufff6\023\ufff6\025\ufff6\026\ufff6\027\ufff6" +
    "\034\ufff6\001\002\000\004\037\046\001\002\000\004\006" +
    "\041\001\002\000\004\006\034\001\002\000\004\006\027" +
    "\001\002\000\004\004\030\001\002\000\004\035\031\001" +
    "\002\000\004\004\032\001\002\000\004\005\033\001\002" +
    "\000\020\010\ufff2\022\ufff2\023\ufff2\025\ufff2\026\ufff2\027" +
    "\ufff2\034\ufff2\001\002\000\004\004\035\001\002\000\004" +
    "\035\036\001\002\000\004\004\037\001\002\000\004\005" +
    "\040\001\002\000\020\010\ufff1\022\ufff1\023\ufff1\025\ufff1" +
    "\026\ufff1\027\ufff1\034\ufff1\001\002\000\004\004\042\001" +
    "\002\000\004\035\043\001\002\000\004\004\044\001\002" +
    "\000\004\005\045\001\002\000\020\010\ufff0\022\ufff0\023" +
    "\ufff0\025\ufff0\026\ufff0\027\ufff0\034\ufff0\001\002\000\004" +
    "\020\047\001\002\000\004\036\050\001\002\000\004\005" +
    "\051\001\002\000\020\010\ufff4\022\ufff4\023\ufff4\025\ufff4" +
    "\026\ufff4\027\ufff4\034\ufff4\001\002\000\004\020\053\001" +
    "\002\000\004\004\054\001\002\000\004\035\055\001\002" +
    "\000\004\004\056\001\002\000\004\005\057\001\002\000" +
    "\020\010\ufff5\022\ufff5\023\ufff5\025\ufff5\026\ufff5\027\ufff5" +
    "\034\ufff5\001\002\000\004\037\061\001\002\000\004\005" +
    "\062\001\002\000\020\010\ufff3\022\ufff3\023\ufff3\025\ufff3" +
    "\026\ufff3\027\ufff3\034\ufff3\001\002\000\016\002\uffed\010" +
    "\uffed\030\uffed\031\uffed\032\uffed\033\uffed\001\002\000\020" +
    "\010\ufff7\022\ufff7\023\ufff7\025\ufff7\026\ufff7\027\ufff7\034" +
    "\ufff7\001\002\000\016\002\uffff\010\uffff\030\uffff\031\uffff" +
    "\032\uffff\033\uffff\001\002\000\016\002\ufff9\010\ufff9\030" +
    "\ufff9\031\ufff9\032\ufff9\033\ufff9\001\002\000\016\002\ufffd" +
    "\010\ufffd\030\ufffd\031\ufffd\032\ufffd\033\ufffd\001\002\000" +
    "\016\002\ufffb\010\ufffb\030\ufffb\031\ufffb\032\ufffb\033\ufffb" +
    "\001\002\000\016\022\021\023\020\025\026\026\025\027" +
    "\024\034\023\001\002\000\020\010\073\022\021\023\020" +
    "\025\026\026\025\027\024\034\023\001\002\000\016\002" +
    "\uffee\010\uffee\030\uffee\031\uffee\032\uffee\033\uffee\001\002" +
    "\000\004\002\001\001\002\000\012\030\006\031\010\032" +
    "\013\033\015\001\002\000\014\010\077\030\006\031\010" +
    "\032\013\033\015\001\002\000\016\002\uffef\010\uffef\030" +
    "\uffef\031\uffef\032\uffef\033\uffef\001\002\000\004\017\101" +
    "\001\002\000\004\035\102\001\002\000\004\017\103\001" +
    "\002\000\004\011\104\001\002\000\004\017\105\001\002" +
    "\000\004\035\106\001\002\000\004\017\107\001\002\000" +
    "\004\013\110\001\002\000\004\005\111\001\002\000\016" +
    "\002\uffec\010\uffec\030\uffec\031\uffec\032\uffec\033\uffec\001" +
    "\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\107\000\016\002\010\004\013\006\004\007\006\010" +
    "\003\011\011\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\006\064\007\066\010\067\011\065\001\001\000\002\001" +
    "\001\000\006\003\021\005\016\001\001\000\004\003\063" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\003" +
    "\021\005\071\001\001\000\004\003\063\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\004\075\006\004\007" +
    "\006\010\003\011\011\001\001\000\012\006\064\007\066" +
    "\010\067\011\065\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintacticoFCA$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintacticoFCA$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintacticoFCA$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}




        //Podemos crear variables, listas, etc;
        // deben de ser staticas si se quieren usar fuera
        
        

        public void syntax_error(Symbol s)
        {
            System.err.println("Error en la Linea " + (s.right+1) +" Columna "+(s.left+1)+ ". Identificador "+s.value + " no reconocido. Se ha recuperado del error." );
        }

        public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception
        {
            System.err.println("Error en la Linea " + (s.right+1)+ " Columna "+(s.left+1)+". Identificador " +s.value + " no reconocido.");
        }
        


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintacticoFCA$actions {

  
  private final SintacticoFCA parser;

  /** Constructor */
  CUP$SintacticoFCA$actions(SintacticoFCA parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintacticoFCA$do_action_part00000000(
    int                        CUP$SintacticoFCA$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoFCA$parser,
    java.util.Stack            CUP$SintacticoFCA$stack,
    int                        CUP$SintacticoFCA$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintacticoFCA$result;

      /* select the action based on the action number */
      switch (CUP$SintacticoFCA$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= INICIO EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)).value;
		RESULT = start_val;
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintacticoFCA$parser.done_parsing();
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // INICIO ::= INSTRUCCIONES 
            {
              Object RESULT =null;
		 
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INICIO",0, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // INSTRUCCIONES ::= INSTRUCCIONES MEIN 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // INSTRUCCIONES ::= MEIN 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // INSTRUCCIONES ::= INSTRUCCIONES DECLARACION_GLOB 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // INSTRUCCIONES ::= DECLARACION_GLOB 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // INSTRUCCIONES ::= INSTRUCCIONES DECLARACION_GRAPH 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // INSTRUCCIONES ::= DECLARACION_GRAPH 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // INSTRUCCIONES ::= INSTRUCCIONES COMPARE 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // INSTRUCCIONES ::= COMPARE 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCIONES",2, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // INST ::= INST INSTRUCCION 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INST",3, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-1)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // INST ::= INSTRUCCION 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INST",3, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // INSTRUCCION ::= string identificador igual cod cadena cod pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-6)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // INSTRUCCION ::= doubleFCA identificador igual digito pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-4)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // INSTRUCCION ::= titulo dop identificador pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // INSTRUCCION ::= titulox dop cod cadena cod pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // INSTRUCCION ::= tituloy dop cod cadena cod pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // INSTRUCCION ::= archivo dop cod cadena cod pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("INSTRUCCION",1, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-5)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // MEIN ::= mein lla INSTRUCCIONES llc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("MEIN",4, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // DECLARACION_GLOB ::= globales lla INST llc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("DECLARACION_GLOB",5, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // DECLARACION_GRAPH ::= graficas lla INST llc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("DECLARACION_GRAPH",6, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-3)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // COMPARE ::= compare cora cosi cadena cosi coma cosi cadena cosi corc pyc 
            {
              Object RESULT =null;
		
              CUP$SintacticoFCA$result = parser.getSymbolFactory().newSymbol("COMPARE",7, ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.elementAt(CUP$SintacticoFCA$top-10)), ((java_cup.runtime.Symbol)CUP$SintacticoFCA$stack.peek()), RESULT);
            }
          return CUP$SintacticoFCA$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintacticoFCA$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintacticoFCA$do_action(
    int                        CUP$SintacticoFCA$act_num,
    java_cup.runtime.lr_parser CUP$SintacticoFCA$parser,
    java.util.Stack            CUP$SintacticoFCA$stack,
    int                        CUP$SintacticoFCA$top)
    throws java.lang.Exception
    {
              return CUP$SintacticoFCA$do_action_part00000000(
                               CUP$SintacticoFCA$act_num,
                               CUP$SintacticoFCA$parser,
                               CUP$SintacticoFCA$stack,
                               CUP$SintacticoFCA$top);
    }
}

}
