
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosFCA {
  /* terminals */
  public static final int string = 13;
  public static final int pyc = 2;
  public static final int parc = 8;
  public static final int cadena = 30;
  public static final int para = 7;
  public static final int decimal = 29;
  public static final int globales = 20;
  public static final int coma = 6;
  public static final int archivo = 17;
  public static final int doubleFCA = 21;
  public static final int pesp = 28;
  public static final int tituloy = 16;
  public static final int titulox = 15;
  public static final int llc = 5;
  public static final int barras = 24;
  public static final int lla = 4;
  public static final int titulo = 14;
  public static final int ejex = 23;
  public static final int mein = 19;
  public static final int digito = 32;
  public static final int pie = 25;
  public static final int igual = 9;
  public static final int EOF = 0;
  public static final int pgen = 27;
  public static final int error = 1;
  public static final int dop = 3;
  public static final int dol = 12;
  public static final int lineas = 26;
  public static final int corc = 11;
  public static final int valores = 22;
  public static final int cora = 10;
  public static final int compare = 18;
  public static final int identificador = 31;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pyc",
  "dop",
  "lla",
  "llc",
  "coma",
  "para",
  "parc",
  "igual",
  "cora",
  "corc",
  "dol",
  "string",
  "titulo",
  "titulox",
  "tituloy",
  "archivo",
  "compare",
  "mein",
  "globales",
  "doubleFCA",
  "valores",
  "ejex",
  "barras",
  "pie",
  "lineas",
  "pgen",
  "pesp",
  "decimal",
  "cadena",
  "identificador",
  "digito"
  };
}

