
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos_JS {
  /* terminals */
  public static final int Op_ari = 4;
  public static final int Else = 15;
  public static final int pyc = 6;
  public static final int parc = 8;
  public static final int cadena = 25;
  public static final int para = 7;
  public static final int For = 16;
  public static final int Op_log = 3;
  public static final int numero = 24;
  public static final int Break = 23;
  public static final int llc = 10;
  public static final int lla = 9;
  public static final int punto = 12;
  public static final int igual = 11;
  public static final int EOF = 0;
  public static final int Case = 22;
  public static final int If = 14;
  public static final int error = 1;
  public static final int variable = 13;
  public static final int dop = 5;
  public static final int Switch = 19;
  public static final int Do = 18;
  public static final int While = 17;
  public static final int ClassJS = 21;
  public static final int Require = 20;
  public static final int Op_rel = 2;
  public static final int identificador = 26;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Op_rel",
  "Op_log",
  "Op_ari",
  "dop",
  "pyc",
  "para",
  "parc",
  "lla",
  "llc",
  "igual",
  "punto",
  "variable",
  "If",
  "Else",
  "For",
  "While",
  "Do",
  "Switch",
  "Require",
  "ClassJS",
  "Case",
  "Break",
  "numero",
  "cadena",
  "identificador"
  };
}

