
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class SimbolosFCA {
  /* terminals */
  public static final int string = 10;
  public static final int pyc = 2;
  public static final int parc = 8;
  public static final int cadena = 21;
  public static final int para = 7;
  public static final int decimal = 20;
  public static final int globales = 17;
  public static final int coma = 6;
  public static final int archivo = 14;
  public static final int doubleFCA = 19;
  public static final int tituloy = 13;
  public static final int titulox = 12;
  public static final int llc = 5;
  public static final int lla = 4;
  public static final int titulo = 11;
  public static final int mein = 16;
  public static final int igual = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int dop = 3;
  public static final int graficas = 18;
  public static final int compare = 15;
  public static final int identificador = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "pyc",
  "dop",
  "lla",
  "llc",
  "coma",
  "para",
  "parc",
  "igual",
  "string",
  "titulo",
  "titulox",
  "tituloy",
  "archivo",
  "compare",
  "mein",
  "globales",
  "graficas",
  "doubleFCA",
  "decimal",
  "cadena",
  "identificador"
  };
}

